"""init admin schema

Revision ID: 3fe8f9f0be96
Revises: 
Create Date: 2026-01-15 15:28:40.501752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe8f9f0be96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Блюда, доступные пользователю.'
    )
    op.create_index(op.f('ix_dish_id'), 'dish', ['id'], unique=False)
    op.create_index(op.f('ix_dish_name'), 'dish', ['name'], unique=True)
    op.create_table('food_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_food_category_code', 'food_category', ['code'], unique=False)
    op.create_table('food',
    sa.Column('fdc_id', sa.Integer(), nullable=False, comment='Уникальный ID продукта FDC'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Название на английском (description)'),
    sa.Column('food_category_id', sa.Integer(), nullable=True, comment='Ссылка на категорию'),
    sa.ForeignKeyConstraint(['food_category_id'], ['food_category.id'], ),
    sa.PrimaryKeyConstraint('fdc_id')
    )
    op.create_table('food_category_ru',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=False),
    sa.Column('description_ru', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['food_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_category_ru_category_id'), 'food_category_ru', ['category_id'], unique=True)
    op.create_table('dish_food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('amount_grams', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['food_id'], ['food.fdc_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Связь блюд с ингредиентами'
    )
    op.create_index(op.f('ix_dish_food_dish_id'), 'dish_food', ['dish_id'], unique=False)
    op.create_index(op.f('ix_dish_food_food_id'), 'dish_food', ['food_id'], unique=False)
    op.create_index(op.f('ix_dish_food_id'), 'dish_food', ['id'], unique=False)
    op.create_table('food_ru',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fdc_id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=False),
    sa.Column('food_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fdc_id'], ['food.fdc_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['food_category_id'], ['food_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_ru_fdc_id'), 'food_ru', ['fdc_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_ru_fdc_id'), table_name='food_ru')
    op.drop_table('food_ru')
    op.drop_index(op.f('ix_dish_food_id'), table_name='dish_food')
    op.drop_index(op.f('ix_dish_food_food_id'), table_name='dish_food')
    op.drop_index(op.f('ix_dish_food_dish_id'), table_name='dish_food')
    op.drop_table('dish_food')
    op.drop_index(op.f('ix_food_category_ru_category_id'), table_name='food_category_ru')
    op.drop_table('food_category_ru')
    op.drop_table('food')
    op.drop_index('idx_food_category_code', table_name='food_category')
    op.drop_table('food_category')
    op.drop_index(op.f('ix_dish_name'), table_name='dish')
    op.drop_index(op.f('ix_dish_id'), table_name='dish')
    op.drop_table('dish')
    # ### end Alembic commands ###
