FROM python:3.11-slim

WORKDIR /app

# Копируем общие зависимости
COPY shared/requirements.txt .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Копируем общие модули
COPY shared/ /app/shared/

# Устанавливаем PYTHONPATH для импортов
ENV PYTHONPATH=/app



# HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 \
#   CMD python -c "import os; from shared.database import engine; engine.connect()" || exit 1
