{
 "title": "Healthy Menu - Логи Backend'ов",
 "tags": [
  "healthy-menu",
  "logs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "Сервис",
    "query": "label_values({namespace=\"healthy-menu-dev\"}, app)"
   },
   {
    "name": "level",
    "label": "Уровень",
    "query": "label_values({namespace=\"healthy-menu-dev\", app=~\"$app\"}, level)"
   }
  ]
 },
 "panels": [
  {
   "title": "Логи Backend'ов",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"healthy-menu-dev\", app=~\".*-backend\"}"
    }
   ]
  },
  {
   "title": "Уровень логирования по времени",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({namespace=\"healthy-menu-dev\", app=~\".*-backend\"} | json | level != \"\" [$__interval]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Количество логов по сервисам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (app) (count_over_time({namespace=\"healthy-menu-dev\", app=~\".*-backend\"} [$__interval]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Всего ошибок",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"healthy-menu-dev\", app=~\".*-backend\"} | json | level=\"error\" [$__range]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Всего Info",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"healthy-menu-dev\", app=~\".*-backend\"} | json | level=\"info\" [$__range]))",
     "legendFormat": "Info"
    }
   ]
  },
  {
   "title": "Всего логов",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"healthy-menu-dev\", app=~\".*-backend\"} [$__range]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Только ошибки",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{namespace=\"healthy-menu-dev\", app=~\".*-backend\"} | json | level=\"error\""
    }
   ]
  }
 ]
}