apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: healthy-menu-dev
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: http://gitlab:8060/ostapkob/gitops.git
      revision: master
      files:
      - path: "services/*.yaml"
  template:
    metadata:
      name: "{{name}}"
    spec:
      project: default
      source:
        repoURL: http://gitlab:8060/ostapkob/infra.git
        targetRevision: master
        path: .
        helm:
          releaseName: "{{name}}"
          parameters:
          - name: image.tag
            value: "{{tag}}"
          - name: service.port
            value: "{{port}}"
          - name: service.targetPort
            value: "{{targetPort}}"
          - name: imagePullSecretName
            value: "nexus-creds"
          - name: vault.enabled
            value: "{{vaultEnabled}}"
          - name: vault.role
            value: "{{vaultRole}}"
          - name: vault.creds[0].credPath
            value: "secret/data/postgres"
          - name: vault.creds[0].secretKeys[0]
            value: "POSTGRES_USER"
          - name: vault.creds[0].secretKeys[1]
            value: "POSTGRES_PASSWORD"
          - name: vault.creds[0].configKeys[0]
            value: "POSTGRES_HOST"
          - name: vault.creds[0].configKeys[1]
            value: "POSTGRES_PORT"
          - name: vault.creds[0].configKeys[2]
            value: "POSTGRES_DB"
          - name: vault.creds[1].credPath
            value: "secret/data/minio"
          - name: vault.creds[1].secretKeys[0]
            value: "MINIO_ROOT_USER"
          - name: vault.creds[1].secretKeys[1]
            value: "MINIO_ROOT_PASSWORD"
          - name: vault.creds[1].configKeys[0]
            value: "MINIO_HOST"
          - name: vault.creds[1].configKeys[1]
            value: "MINIO_PORT"
          - name: vault.creds[1].configKeys[2]
            value: "MINIO_BUCKET"
          # Istio configuration
          - name: istio.enabled
            value: "{{istioEnabled}}"
          - name: istio.peerAuthentication.mode
            value: "{{istioPeerAuthMode}}"
          - name: istio.authorizationPolicy.allowInternal
            value: "{{istioAllowInternal}}"

      destination:
        server: https://kubernetes.default.svc
        namespace: healthy-menu-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
