---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: admin-backend
  namespace: healthy-menu-dev
spec:
  host: admin-backend.healthy-menu-dev.svc.cluster.local
  trafficPolicy:
    connectionPool:           # Ограничения подключений
      http:
        http1MaxPendingRequests: 100
        maxRequestsPerConnection: 100
    outlierDetection:         # Circuit Breaker
      consecutive5xxErrors: 5  # 5 ошибок подряд 5xx
      interval: 10s           # проверять каждые 10 сек
      baseEjectionTime: 30s   # исключить из пула на 30 сек
      maxEjectionPercent: 50  # максимум 50% подов

---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: order-backend
  namespace: healthy-menu-dev
spec:
  host: order-backend.healthy-menu-dev.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 100
        maxRequestsPerConnection: 100
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: courier-backend
  namespace: healthy-menu-dev
spec:
  host: courier-backend.healthy-menu-dev.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 100
        maxRequestsPerConnection: 100
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
