# Порт 8080 используется потому, что istio-ingressgateway слушает на 8080
# Внешний порт мапится на 8080 внутри кластера
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: healthy-menu-gateway
  namespace: healthy-menu-dev
spec:
  selector:
    istio: ingressgateway # Только для istio-ingressgateway подов
  servers:
    - port:
        number: 8080 # Внешний порт (NodePort)
        name: http
        protocol: HTTP
      hosts:
        - healthy-menu.local # Только запросы с этим Host заголовком
