"""add code to Nutrient

Revision ID: 1c5e8fdbebe0
Revises: abf9037c93a3
Create Date: 2025-12-11 16:05:08.839644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c5e8fdbebe0'
down_revision: Union[str, Sequence[str], None] = 'abf9037c93a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrients', sa.Column('code', sa.String(), nullable=False, comment="Стойкий код нутриента для API: 'vitamin_a', 'vitamin_c', 'calcium' и т.п."))
    op.create_unique_constraint(None, 'nutrients', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nutrients', type_='unique')
    op.drop_column('nutrients', 'code')
    # ### end Alembic commands ###
