"""add  photo_url

Revision ID: 1e26a8f13b72
Revises: 2b2a20f8fbd5
Create Date: 2025-12-14 15:31:05.826684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e26a8f13b72'
down_revision: Union[str, Sequence[str], None] = '2b2a20f8fbd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('couriers', sa.Column('photo_url', sa.String(), nullable=True))
    op.drop_index(op.f('ix_couriers_id'), table_name='couriers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_couriers_id'), 'couriers', ['id'], unique=False)
    op.drop_column('couriers', 'photo_url')
    # ### end Alembic commands ###
