"""dish

Revision ID: 6381626f6928
Revises:
Create Date: 2026-01-07 14:37:04.575307

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6381626f6928"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "couriers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("current_order_id", sa.Integer(), nullable=True),
        sa.Column("photo_url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dish",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price", sa.Numeric(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        comment="Блюда, доступные пользователю.",
    )
    op.create_index(op.f("ix_dish_id"), "dish", ["id"], unique=False)
    op.create_index(op.f("ix_dish_name"), "dish", ["name"], unique=True)
    op.create_table(
        "food_category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        "idx_food_category_code", "food_category", ["code"], unique=False
    )
    op.create_table(
        "nutrient",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
            comment="Уникальный ID нутриента в FDC",
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Название на английском",
        ),
        sa.Column(
            "unit_name",
            sa.String(length=50),
            nullable=True,
            comment="Единица измерения (g, mg, mcg, IU)",
        ),
        sa.Column(
            "nutrient_nbr",
            sa.Float(),
            nullable=True,
            comment="Старый номер нутриента из SR Legacy",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column(
            "total_price", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_id"), "orders", ["id"], unique=False)
    op.create_table(
        "daily_norms",
        sa.Column("nutrient_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("unit_name", sa.String(length=50), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["nutrient_id"],
            ["nutrient.id"],
        ),
        sa.PrimaryKeyConstraint("nutrient_id"),
    )
    op.create_table(
        "deliveries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("courier_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column(
            "assigned_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "picked_up_at", postgresql.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.Column(
            "delivered_at", postgresql.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["courier_id"],
            ["couriers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deliveries_id"), "deliveries", ["id"], unique=False
    )
    op.create_table(
        "food",
        sa.Column(
            "fdc_id",
            sa.Integer(),
            nullable=False,
            comment="Уникальный ID продукта FDC",
        ),
        sa.Column(
            "description",
            sa.String(length=500),
            nullable=True,
            comment="Название на английском (description)",
        ),
        sa.Column(
            "food_category_id",
            sa.Integer(),
            nullable=True,
            comment="Ссылка на категорию",
        ),
        sa.ForeignKeyConstraint(
            ["food_category_id"],
            ["food_category.id"],
        ),
        sa.PrimaryKeyConstraint("fdc_id"),
    )
    op.create_table(
        "food_category_ru",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("name_ru", sa.String(length=255), nullable=False),
        sa.Column("description_ru", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["food_category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_food_category_ru_category_id"),
        "food_category_ru",
        ["category_id"],
        unique=True,
    )
    op.create_table(
        "nutrient_ru",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nutrient_id", sa.Integer(), nullable=False),
        sa.Column("name_ru", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["nutrient_id"],
            ["nutrient.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_nutrient_ru_nutrient_id"),
        "nutrient_ru",
        ["nutrient_id"],
        unique=True,
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("dish_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["dish_id"],
            ["dish.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_items_id"), "order_items", ["id"], unique=False
    )
    op.create_table(
        "dish_food",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dish_id", sa.Integer(), nullable=False),
        sa.Column("food_id", sa.Integer(), nullable=False),
        sa.Column("amount_grams", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["dish_id"], ["dish.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["food_id"], ["food.fdc_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Связь блюд с ингредиентами",
    )
    op.create_index(
        op.f("ix_dish_food_dish_id"), "dish_food", ["dish_id"], unique=False
    )
    op.create_index(
        op.f("ix_dish_food_food_id"), "dish_food", ["food_id"], unique=False
    )
    op.create_index(op.f("ix_dish_food_id"), "dish_food", ["id"], unique=False)
    op.create_table(
        "food_nutrient",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fdc_id", sa.Integer(), nullable=False),
        sa.Column("nutrient_id", sa.Integer(), nullable=False),
        sa.Column(
            "amount",
            sa.Numeric(precision=10, scale=4),
            nullable=True,
            comment="Нутриента на 100г продукта",
        ),
        sa.Column("data_points", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fdc_id"], ["food.fdc_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["nutrient_id"], ["nutrient.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_food_nutr_composite",
        "food_nutrient",
        ["fdc_id", "nutrient_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_food_nutrient_fdc_id"),
        "food_nutrient",
        ["fdc_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_food_nutrient_nutrient_id"),
        "food_nutrient",
        ["nutrient_id"],
        unique=False,
    )
    op.create_table(
        "food_ru",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fdc_id", sa.Integer(), nullable=False),
        sa.Column("name_ru", sa.String(length=255), nullable=False),
        sa.Column("food_category_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fdc_id"], ["food.fdc_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["food_category_id"],
            ["food_category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_food_ru_fdc_id"), "food_ru", ["fdc_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_food_ru_fdc_id"), table_name="food_ru")
    op.drop_table("food_ru")
    op.drop_index(
        op.f("ix_food_nutrient_nutrient_id"), table_name="food_nutrient"
    )
    op.drop_index(op.f("ix_food_nutrient_fdc_id"), table_name="food_nutrient")
    op.drop_index("idx_food_nutr_composite", table_name="food_nutrient")
    op.drop_table("food_nutrient")
    op.drop_index(op.f("ix_dish_food_id"), table_name="dish_food")
    op.drop_index(op.f("ix_dish_food_food_id"), table_name="dish_food")
    op.drop_index(op.f("ix_dish_food_dish_id"), table_name="dish_food")
    op.drop_table("dish_food")
    op.drop_index(op.f("ix_order_items_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_nutrient_ru_nutrient_id"), table_name="nutrient_ru")
    op.drop_table("nutrient_ru")
    op.drop_index(
        op.f("ix_food_category_ru_category_id"), table_name="food_category_ru"
    )
    op.drop_table("food_category_ru")
    op.drop_table("food")
    op.drop_index(op.f("ix_deliveries_id"), table_name="deliveries")
    op.drop_table("deliveries")
    op.drop_table("daily_norms")
    op.drop_index(op.f("ix_orders_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_table("nutrient")
    op.drop_index("idx_food_category_code", table_name="food_category")
    op.drop_table("food_category")
    op.drop_index(op.f("ix_dish_name"), table_name="dish")
    op.drop_index(op.f("ix_dish_id"), table_name="dish")
    op.drop_table("dish")
    op.drop_table("couriers")
    # ### end Alembic commands ###
