"""new column in menu

Revision ID: 6404e83246a2
Revises: d1cb97ab4d13
Create Date: 2025-12-11 14:45:11.327166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6404e83246a2'
down_revision: Union[str, Sequence[str], None] = 'd1cb97ab4d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrients',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор нутриента.'),
    sa.Column('name', sa.String(), nullable=False, comment="Полное название нутриента (например, 'Витамин A (РЭ)', 'Кальций')."),
    sa.Column('short_name', sa.String(), nullable=False, comment='Краткое обозначение нутриента (A, C, D, Ca, Fe и т.п.).'),
    sa.Column('type', sa.String(), nullable=False, comment="Тип нутриента: 'vitamin' или 'mineral'."),
    sa.Column('unit', sa.String(), nullable=False, comment='Единица измерения нутриента (мг, мкг, мг и т.п.).'),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник витаминов и минералов (нутриентов), используемых в расчётах.'
    )
    op.create_index(op.f('ix_nutrients_id'), 'nutrients', ['id'], unique=False)
    op.create_index(op.f('ix_nutrients_name'), 'nutrients', ['name'], unique=True)
    op.create_table('daily_nutrient_requirements',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор записи нормы.'),
    sa.Column('nutrient_id', sa.Integer(), nullable=False, comment='FK на нутриент, для которого задаётся норма.'),
    sa.Column('amount', sa.Float(), nullable=False, comment='Рекомендуемое количество нутриента в сутки.'),
    sa.Column('age_group', sa.String(), nullable=False, comment="Возрастная группа (например, 'взрослый')."),
    sa.ForeignKeyConstraint(['nutrient_id'], ['nutrients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Суточные рекомендуемые нормы нутриентов по возрастным группам.'
    )
    op.create_index(op.f('ix_daily_nutrient_requirements_id'), 'daily_nutrient_requirements', ['id'], unique=False)
    op.create_table('ingredient_nutrient_contents',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор записи содержания нутриента.'),
    sa.Column('ingredient_id', sa.Integer(), nullable=False, comment='FK на ингредиент.'),
    sa.Column('nutrient_id', sa.Integer(), nullable=False, comment='FK на нутриент (витамин или минерал).'),
    sa.Column('content_per_100g', sa.Float(), nullable=False, comment='Кол-во нутриента на 100 г ингредиента (в единицах из nutrients.unit).'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['nutrient_id'], ['nutrients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица содержания нутриентов в ингредиентах на 100 грамм.'
    )
    op.create_index(op.f('ix_ingredient_nutrient_contents_id'), 'ingredient_nutrient_contents', ['id'], unique=False)
    op.create_table('nutrient_organ_benefits',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор записи пользы.'),
    sa.Column('nutrient_id', sa.Integer(), nullable=False, comment='FK на нутриент (витамин/минерал), оказывающий эффект.'),
    sa.Column('organ_id', sa.Integer(), nullable=False, comment='FK на орган, на который влияет нутриент.'),
    sa.Column('benefit_note', sa.String(), nullable=False, comment='Краткое описание пользы нутриента для органа.'),
    sa.ForeignKeyConstraint(['nutrient_id'], ['nutrients.id'], ),
    sa.ForeignKeyConstraint(['organ_id'], ['organs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Текстовые описания пользы нутриентов для конкретных органов.'
    )
    op.create_index(op.f('ix_nutrient_organ_benefits_id'), 'nutrient_organ_benefits', ['id'], unique=False)
    op.drop_index(op.f('ix_daily_vitamin_requirements_id'), table_name='daily_vitamin_requirements')
    op.drop_table('daily_vitamin_requirements')
    op.drop_index(op.f('ix_ingredient_vitamin_contents_id'), table_name='ingredient_vitamin_contents')
    op.drop_table('ingredient_vitamin_contents')
    op.drop_index(op.f('ix_vitamin_organ_benefits_id'), table_name='vitamin_organ_benefits')
    op.drop_table('vitamin_organ_benefits')
    op.drop_index(op.f('ix_vitamins_id'), table_name='vitamins')
    op.drop_index(op.f('ix_vitamins_name'), table_name='vitamins')
    op.drop_table('vitamins')
    op.alter_column('dish_ingredients', 'id',
               existing_type=sa.INTEGER(),
               comment='Уникальный идентификатор записи состава блюда.',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('dish_ingredients', 'dish_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='FK на блюдо.')
    op.alter_column('dish_ingredients', 'ingredient_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='FK на ингредиент.')
    op.alter_column('dish_ingredients', 'amount_grams',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               comment='Масса ингредиента в блюде (граммы).')
    op.create_table_comment(
        'dish_ingredients',
        'Связь блюд с ингредиентами и их массой в рецепте.',
        existing_comment=None,
        schema=None
    )
    op.alter_column('dishes', 'id',
               existing_type=sa.INTEGER(),
               comment='Уникальный идентификатор блюда.',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('dishes_id_seq'::regclass)"))
    op.alter_column('dishes', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment="Название блюда (например, 'Куриное филе с брокколи').")
    op.alter_column('dishes', 'price',
               existing_type=sa.NUMERIC(),
               nullable=False,
               comment='Стоимость блюда в валюте сервиса.')
    op.create_table_comment(
        'dishes',
        'Блюда, доступные пользователю (связаны с ингредиентами и ценой).',
        existing_comment=None,
        schema=None
    )
    op.alter_column('ingredients', 'id',
               existing_type=sa.INTEGER(),
               comment='Уникальный идентификатор ингредиента.',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('ingredients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment="Название ингредиента (например, 'Куриное филе', 'Брокколи').")
    op.create_table_comment(
        'ingredients',
        'Ингредиенты, используемые в блюдах (содержат калории и нутриенты).',
        existing_comment=None,
        schema=None
    )
    op.alter_column('organs', 'id',
               existing_type=sa.INTEGER(),
               comment='Уникальный идентификатор органа.',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('organs', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment="Название органа (например, 'Печень', 'Сердце').")
    op.alter_column('organs', 'description',
               existing_type=sa.VARCHAR(),
               comment='Краткое описание функции органа.',
               existing_nullable=True)
    op.create_table_comment(
        'organs',
        'Целевые органы и системы организма (печень, сердце, мозг и т.п.).',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'organs',
        existing_comment='Целевые органы и системы организма (печень, сердце, мозг и т.п.).',
        schema=None
    )
    op.alter_column('organs', 'description',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Краткое описание функции органа.',
               existing_nullable=True)
    op.alter_column('organs', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment=None,
               existing_comment="Название органа (например, 'Печень', 'Сердце').")
    op.alter_column('organs', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Уникальный идентификатор органа.',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'ingredients',
        existing_comment='Ингредиенты, используемые в блюдах (содержат калории и нутриенты).',
        schema=None
    )
    op.alter_column('ingredients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment=None,
               existing_comment="Название ингредиента (например, 'Куриное филе', 'Брокколи').")
    op.alter_column('ingredients', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Уникальный идентификатор ингредиента.',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'dishes',
        existing_comment='Блюда, доступные пользователю (связаны с ингредиентами и ценой).',
        schema=None
    )
    op.alter_column('dishes', 'price',
               existing_type=sa.NUMERIC(),
               nullable=True,
               comment=None,
               existing_comment='Стоимость блюда в валюте сервиса.')
    op.alter_column('dishes', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment=None,
               existing_comment="Название блюда (например, 'Куриное филе с брокколи').")
    op.alter_column('dishes', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Уникальный идентификатор блюда.',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('dishes_id_seq'::regclass)"))
    op.drop_table_comment(
        'dish_ingredients',
        existing_comment='Связь блюд с ингредиентами и их массой в рецепте.',
        schema=None
    )
    op.alter_column('dish_ingredients', 'amount_grams',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               comment=None,
               existing_comment='Масса ингредиента в блюде (граммы).')
    op.alter_column('dish_ingredients', 'ingredient_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='FK на ингредиент.')
    op.alter_column('dish_ingredients', 'dish_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='FK на блюдо.')
    op.alter_column('dish_ingredients', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Уникальный идентификатор записи состава блюда.',
               existing_nullable=False,
               autoincrement=True)
    op.create_table('vitamins',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('vitamins_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('short_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vitamins_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_vitamins_name'), 'vitamins', ['name'], unique=True)
    op.create_index(op.f('ix_vitamins_id'), 'vitamins', ['id'], unique=False)
    op.create_table('vitamin_organ_benefits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vitamin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('organ_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('benefit_note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organ_id'], ['organs.id'], name=op.f('vitamin_organ_benefits_organ_id_fkey')),
    sa.ForeignKeyConstraint(['vitamin_id'], ['vitamins.id'], name=op.f('vitamin_organ_benefits_vitamin_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vitamin_organ_benefits_pkey'))
    )
    op.create_index(op.f('ix_vitamin_organ_benefits_id'), 'vitamin_organ_benefits', ['id'], unique=False)
    op.create_table('ingredient_vitamin_contents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vitamin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content_per_100g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('ingredient_vitamin_contents_ingredient_id_fkey')),
    sa.ForeignKeyConstraint(['vitamin_id'], ['vitamins.id'], name=op.f('ingredient_vitamin_contents_vitamin_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ingredient_vitamin_contents_pkey'))
    )
    op.create_index(op.f('ix_ingredient_vitamin_contents_id'), 'ingredient_vitamin_contents', ['id'], unique=False)
    op.create_table('daily_vitamin_requirements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vitamin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age_group', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['vitamin_id'], ['vitamins.id'], name=op.f('daily_vitamin_requirements_vitamin_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_vitamin_requirements_pkey'))
    )
    op.create_index(op.f('ix_daily_vitamin_requirements_id'), 'daily_vitamin_requirements', ['id'], unique=False)
    op.drop_index(op.f('ix_nutrient_organ_benefits_id'), table_name='nutrient_organ_benefits')
    op.drop_table('nutrient_organ_benefits')
    op.drop_index(op.f('ix_ingredient_nutrient_contents_id'), table_name='ingredient_nutrient_contents')
    op.drop_table('ingredient_nutrient_contents')
    op.drop_index(op.f('ix_daily_nutrient_requirements_id'), table_name='daily_nutrient_requirements')
    op.drop_table('daily_nutrient_requirements')
    op.drop_index(op.f('ix_nutrients_name'), table_name='nutrients')
    op.drop_index(op.f('ix_nutrients_id'), table_name='nutrients')
    op.drop_table('nutrients')
    # ### end Alembic commands ###
