"""add image_url to dishes

Revision ID: 75f2b113854e
Revises: 9dc7bbfb08af
Create Date: 2025-12-11 23:18:28.753505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f2b113854e'
down_revision: Union[str, Sequence[str], None] = '9dc7bbfb08af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dishes', 'image_url')
    # ### end Alembic commands ###
