"""add nutrient model and fields to dishes/ingredients

Revision ID: abf9037c93a3
Revises: 6404e83246a2
Create Date: 2025-12-11 15:27:37.084491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abf9037c93a3'
down_revision: Union[str, Sequence[str], None] = '6404e83246a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('description', sa.String(), nullable=True, comment='Краткое описание блюда (ингредиенты, способ приготовления).'))
    op.alter_column('dishes', 'id',
               existing_type=sa.INTEGER(),
               comment='ID блюда.',
               existing_comment='Уникальный идентификатор блюда.',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('dishes_id_seq'::regclass)"))
    op.alter_column('dishes', 'name',
               existing_type=sa.VARCHAR(),
               comment='Название блюда.',
               existing_comment="Название блюда (например, 'Куриное филе с брокколи').",
               existing_nullable=False)
    op.alter_column('dishes', 'price',
               existing_type=sa.NUMERIC(),
               comment='Цена блюда.',
               existing_comment='Стоимость блюда в валюте сервиса.',
               existing_nullable=False)
    op.create_table_comment(
        'dishes',
        'Блюда, доступные пользователю.',
        existing_comment='Блюда, доступные пользователю (связаны с ингредиентами и ценой).',
        schema=None
    )
    op.add_column('ingredients', sa.Column('category', sa.String(), nullable=True, comment='Категория ингредиента (овощи, белки, орехи, масла и т.п.).'))
    op.alter_column('ingredients', 'id',
               existing_type=sa.INTEGER(),
               comment='ID ингредиента.',
               existing_comment='Уникальный идентификатор ингредиента.',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('ingredients', 'name',
               existing_type=sa.VARCHAR(),
               comment='Название ингредиента.',
               existing_comment="Название ингредиента (например, 'Куриное филе', 'Брокколи').",
               existing_nullable=False)
    op.create_table_comment(
        'ingredients',
        'Ингредиенты, используемые в блюдах.',
        existing_comment='Ингредиенты, используемые в блюдах (содержат калории и нутриенты).',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'ingredients',
        'Ингредиенты, используемые в блюдах (содержат калории и нутриенты).',
        existing_comment='Ингредиенты, используемые в блюдах.',
        schema=None
    )
    op.alter_column('ingredients', 'name',
               existing_type=sa.VARCHAR(),
               comment="Название ингредиента (например, 'Куриное филе', 'Брокколи').",
               existing_comment='Название ингредиента.',
               existing_nullable=False)
    op.alter_column('ingredients', 'id',
               existing_type=sa.INTEGER(),
               comment='Уникальный идентификатор ингредиента.',
               existing_comment='ID ингредиента.',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('ingredients', 'category')
    op.create_table_comment(
        'dishes',
        'Блюда, доступные пользователю (связаны с ингредиентами и ценой).',
        existing_comment='Блюда, доступные пользователю.',
        schema=None
    )
    op.alter_column('dishes', 'price',
               existing_type=sa.NUMERIC(),
               comment='Стоимость блюда в валюте сервиса.',
               existing_comment='Цена блюда.',
               existing_nullable=False)
    op.alter_column('dishes', 'name',
               existing_type=sa.VARCHAR(),
               comment="Название блюда (например, 'Куриное филе с брокколи').",
               existing_comment='Название блюда.',
               existing_nullable=False)
    op.alter_column('dishes', 'id',
               existing_type=sa.INTEGER(),
               comment='Уникальный идентификатор блюда.',
               existing_comment='ID блюда.',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('dishes_id_seq'::regclass)"))
    op.drop_column('dishes', 'description')
    # ### end Alembic commands ###
