"""create all tables

Revision ID: c51a8d0fdfb4
Revises: 
Create Date: 2025-11-25 17:54:02.982582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51a8d0fdfb4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dishes_id'), 'dishes', ['id'], unique=False)
    op.create_index(op.f('ix_dishes_name'), 'dishes', ['name'], unique=True)
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_id'), 'ingredients', ['id'], unique=False)
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=True)
    op.create_table('organs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organs_id'), 'organs', ['id'], unique=False)
    op.create_index(op.f('ix_organs_name'), 'organs', ['name'], unique=True)
    op.create_table('vitamins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vitamins_id'), 'vitamins', ['id'], unique=False)
    op.create_index(op.f('ix_vitamins_name'), 'vitamins', ['name'], unique=True)
    op.create_table('daily_vitamin_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vitamin_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('age_group', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vitamin_id'], ['vitamins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_vitamin_requirements_id'), 'daily_vitamin_requirements', ['id'], unique=False)
    op.create_table('dish_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('amount_grams', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dish_ingredients_id'), 'dish_ingredients', ['id'], unique=False)
    op.create_table('ingredient_vitamin_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('vitamin_id', sa.Integer(), nullable=True),
    sa.Column('content_per_100g', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['vitamin_id'], ['vitamins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_vitamin_contents_id'), 'ingredient_vitamin_contents', ['id'], unique=False)
    op.create_table('vitamin_organ_benefits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vitamin_id', sa.Integer(), nullable=True),
    sa.Column('organ_id', sa.Integer(), nullable=True),
    sa.Column('benefit_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organ_id'], ['organs.id'], ),
    sa.ForeignKeyConstraint(['vitamin_id'], ['vitamins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vitamin_organ_benefits_id'), 'vitamin_organ_benefits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vitamin_organ_benefits_id'), table_name='vitamin_organ_benefits')
    op.drop_table('vitamin_organ_benefits')
    op.drop_index(op.f('ix_ingredient_vitamin_contents_id'), table_name='ingredient_vitamin_contents')
    op.drop_table('ingredient_vitamin_contents')
    op.drop_index(op.f('ix_dish_ingredients_id'), table_name='dish_ingredients')
    op.drop_table('dish_ingredients')
    op.drop_index(op.f('ix_daily_vitamin_requirements_id'), table_name='daily_vitamin_requirements')
    op.drop_table('daily_vitamin_requirements')
    op.drop_index(op.f('ix_vitamins_name'), table_name='vitamins')
    op.drop_index(op.f('ix_vitamins_id'), table_name='vitamins')
    op.drop_table('vitamins')
    op.drop_index(op.f('ix_organs_name'), table_name='organs')
    op.drop_index(op.f('ix_organs_id'), table_name='organs')
    op.drop_table('organs')
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_id'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_dishes_name'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_id'), table_name='dishes')
    op.drop_table('dishes')
    # ### end Alembic commands ###
