"""IngredientCalories

Revision ID: ed429413838e
Revises: f892cab457f1
Create Date: 2025-12-11 16:59:08.640877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed429413838e'
down_revision: Union[str, Sequence[str], None] = 'f892cab457f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_calories',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор записи калорийности.'),
    sa.Column('ingredient_id', sa.Integer(), nullable=False, comment='FK на ингредиент (одна запись калорийности на ингредиент).'),
    sa.Column('calories_per_100g', sa.Float(), nullable=False, comment='Энергетическая ценность на 100 г ингредиента (ккал).'),
    sa.Column('protein_g', sa.Float(), nullable=False, comment='Белки на 100 г (г).'),
    sa.Column('fat_g', sa.Float(), nullable=False, comment='Жиры на 100 г (г).'),
    sa.Column('carbs_g', sa.Float(), nullable=False, comment='Углеводы на 100 г (г).'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id'),
    comment='Калории и макронутриенты ингредиентов на 100 г.'
    )
    op.create_index(op.f('ix_ingredient_calories_id'), 'ingredient_calories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredient_calories_id'), table_name='ingredient_calories')
    op.drop_table('ingredient_calories')
    # ### end Alembic commands ###
