---
# ServiceAccount для приложения
# Используется для аутентификации в Vault через K8s auth method
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    description: "ServiceAccount для {{ .Release.Name }} (Vault role: {{ .Release.Name }}-role)"
