{{- if and .Values.vault.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    vault.security.banzaicloud.io/vault-addr: "{{ .Values.vault.addr }}"
    vault.security.banzaicloud.io/vault-skip-verify: "{{ .Values.vault.skipVerify }}"
    vault.security.banzaicloud.io/vault-path: "{{ .Values.vault.authPath }}"
    vault.security.banzaicloud.io/vault-role: "{{ .Values.vault.role }}"
    vault.security.banzaicloud.io/vault-serviceaccount: "{{ .Release.Name }}"
    vault.security.banzaicloud.io/vault-env-from-path: "{{ .Values.vault.envFromPath }}"
    vault.security.banzaicloud.io/vault-auth-method: "{{ .Values.vault.vaultAuthMethod }}"
type: Opaque
stringData:
  MINIO_ROOT_PASSWORD: vault:secret/data/minio#MINIO_ROOT_PASSWORD
  MINIO_ROOT_USER: vault:secret/data/minio#MINIO_ROOT_USER
  POSTGRES_PASSWORD: vault:secret/data/postgres#POSTGRES_PASSWORD
  POSTGRES_USER: vault:secret/data/postgres#POSTGRES_USER
{{- end }}
